
import React, { useMemo, useEffect, useState, useRef } from 'react';
import { InfoItem } from '../../types';
import { DocumentTextIcon, ArrowRightIcon, DownloadIcon, SparklesIcon, CloseIcon, CheckIcon } from '../icons';
import { getArticleHtml, downloadArticlePdf } from '../../api/intelligence';

// 为从CDN加载的 `marked` 库提供类型声明
declare global {
  interface Window {
    marked?: {
      parse(markdownString: string): string;
    };
  }
}

interface EvidenceTrailProps {
    selectedArticle: InfoItem | null;
}

export const EvidenceTrail: React.FC<EvidenceTrailProps> = ({ selectedArticle }) => {
    const [htmlContent, setHtmlContent] = useState<string | null>(null);
    const [isLoadingHtml, setIsLoadingHtml] = useState(false);
    const [isDownloading, setIsDownloading] = useState(false);
    const [showTip, setShowTip] = useState(true);
    const iframeRef = useRef<HTMLIFrameElement>(null);
    const contentRef = useRef<HTMLDivElement>(null);

    // Reset view when article changes and fetch HTML
    useEffect(() => {
        if (contentRef.current) {
            contentRef.current.scrollTop = 0;
        }
        
        setHtmlContent(null);
        
        // Check for valid ID (not a temporary random ID generated by frontend, marked with 'temp_')
        // This prevents 404 errors when using random IDs from semantic search results
        const isTempId = selectedArticle?.id && String(selectedArticle.id).startsWith('temp_');
        
        if (selectedArticle && !isTempId) {
            setIsLoadingHtml(true);
            getArticleHtml(selectedArticle.id)
                .then((html) => {
                    if (html) {
                        // Inject specific styles. 
                        // Updated: Set max-width to 100% to fill the container instead of fixed 800px.
                        const printStyles = `
                            <style>
                                body { 
                                    font-family: 'HarmonyOS Sans SC', "Microsoft YaHei", "PingFang SC", -apple-system, sans-serif; 
                                    line-height: 1.75; 
                                    color: #1f2937; 
                                    padding: 40px;
                                    max-width: 100%; 
                                    margin: 0;
                                    background-color: white;
                                    box-sizing: border-box;
                                }
                                img { max-width: 100%; border-radius: 12px; box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1); margin: 24px 0; }
                                h1 { font-size: 28px; color: #111827; margin-bottom: 20px; font-weight: 800; letter-spacing: -0.025em; }
                                h2 { font-size: 22px; color: #1f2937; margin-top: 36px; margin-bottom: 16px; padding-bottom: 8px; border-bottom: 2px solid #f3f4f6; font-weight: 700; }
                                h3 { font-size: 18px; color: #374151; margin-top: 24px; margin-bottom: 12px; font-weight: 600; }
                                p { margin-bottom: 16px; text-align: justify; color: #4b5563; }
                                blockquote { border-left: 4px solid #6366f1; background: #eef2ff; padding: 16px 20px; margin: 24px 0; border-radius: 0 12px 12px 0; color: #4338ca; font-style: italic; }
                                table { border-collapse: collapse; width: 100%; margin: 24px 0; border-radius: 8px; overflow: hidden; font-size: 14px; }
                                th, td { border: 1px solid #e5e7eb; padding: 12px; text-align: left; }
                                th { background-color: #f9fafb; font-weight: 600; color: #111827; }
                                td { color: #4b5563; }
                                ul, ol { margin-bottom: 16px; padding-left: 24px; color: #4b5563; }
                                li { margin-bottom: 8px; }
                                
                                /* Optimize for printing */
                                @media print {
                                    body { padding: 0; margin: 0; }
                                }
                            </style>
                        `;
                        setHtmlContent(printStyles + html);
                    } else {
                        setHtmlContent(null);
                    }
                })
                .catch((err) => {
                    console.error("Failed to fetch article HTML", err);
                })
                .finally(() => {
                    setIsLoadingHtml(false);
                });
        }
    }, [selectedArticle]);

    // Handle Export PDF using Backend API
    const handleDownloadPdf = async () => {
        if (!selectedArticle) return;
        
        // Check for temp ID
        if (String(selectedArticle.id).startsWith('temp_')) {
             alert("该内容尚未入库，无法生成PDF。");
             return;
        }

        setIsDownloading(true);
        try {
            const blob = await downloadArticlePdf(selectedArticle.id);
            const url = window.URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = `${selectedArticle.title || 'report'}.pdf`;
            document.body.appendChild(a);
            a.click();
            a.remove();
            window.URL.revokeObjectURL(url);
        } catch (err: any) {
            console.error("PDF Download Error:", err);
            alert(err.message || "PDF 下载失败，请重试。");
        } finally {
            setIsDownloading(false);
        }
    };

    const fallbackArticleHtml = useMemo(() => {
        if (!selectedArticle || !selectedArticle.content) {
            return '';
        }

        if (window.marked && typeof window.marked.parse === 'function') {
            const markdownWithStyledImages = selectedArticle.content.replace(
                /!\[(.*?)\]\((.*?)\)/g,
                '<figure class="my-6"><img src="$2" alt="$1" class="rounded-2xl w-full object-cover shadow-sm"><figcaption class="text-center text-xs text-gray-500 mt-2">$1</figcaption></figure>'
            );
            return window.marked.parse(markdownWithStyledImages);
        }

        console.warn("marked.js is not available. Falling back to plain text with line breaks.");
        const escapedContent = selectedArticle.content
            .replace(/&/g, "&amp;")
            .replace(/</g, "&lt;")
            .replace(/>/g, "&gt;");
        return escapedContent.split('\n').map(p => `<p>${p}</p>`).join('');

    }, [selectedArticle]);

    if (!selectedArticle) {
        return (
            <div className="h-full flex flex-col items-center justify-center text-center p-8 bg-white">
                <div className="w-24 h-24 bg-slate-50 rounded-full flex items-center justify-center mb-6 shadow-sm">
                    <DocumentTextIcon className="w-12 h-12 text-slate-300" />
                </div>
                <h3 className="font-bold text-2xl text-slate-800 mb-3">AI 智能研报</h3>
                <p className="text-slate-500 max-w-[240px] leading-relaxed text-sm">
                    请从左侧选择一项情报。<br/>
                    AI 将为您呈现结构化、可视化的深度分析报告。
                </p>
            </div>
        );
    }

    return (
        <aside className="h-full flex flex-col bg-white overflow-hidden transition-all duration-500 relative">
            {/* Header Area */}
            <div className="p-5 md:p-8 bg-white flex-shrink-0 border-b border-slate-100 z-20 shadow-[0_4px_20px_-10px_rgba(0,0,0,0.05)]">
                <div className="flex flex-col gap-5">
                    <div>
                        <div className="flex items-center gap-3 mb-3">
                            <span className="inline-flex items-center px-2.5 py-1 rounded-lg text-xs font-bold bg-indigo-50 text-indigo-600 border border-indigo-100">
                                {selectedArticle.source_name}
                            </span>
                            <span className="text-xs text-slate-400 font-medium">
                                {new Date(selectedArticle.publish_date || selectedArticle.created_at).toLocaleDateString('zh-CN', {year: 'numeric', month: 'long', day: 'numeric'})}
                            </span>
                        </div>
                        <h3 className="font-extrabold text-slate-900 text-xl md:text-3xl leading-tight tracking-tight">
                            {selectedArticle.title}
                        </h3>
                    </div>
                    
                    <div className="flex flex-col sm:flex-row sm:items-center gap-4">
                        {/* Main Action Button */}
                        {htmlContent && (
                            <button 
                                onClick={handleDownloadPdf}
                                disabled={isDownloading}
                                className="relative group flex-1 md:flex-none inline-flex items-center justify-center gap-2 px-6 py-3 text-sm font-bold text-white bg-gradient-to-r from-indigo-600 to-blue-600 rounded-xl hover:shadow-lg hover:shadow-indigo-500/30 transition-all duration-300 transform active:scale-95 disabled:opacity-70 disabled:cursor-wait overflow-hidden"
                                title="下载适合汇报的 PDF 文档"
                            >
                                <div className="absolute inset-0 bg-white/20 group-hover:translate-x-full transition-transform duration-500 ease-in-out -translate-x-full skew-x-12"></div>
                                {isDownloading ? (
                                    <>
                                        <div className="animate-spin w-4 h-4 border-2 border-white/30 border-t-white rounded-full"></div>
                                        <span>生成中...</span>
                                    </>
                                ) : (
                                    <>
                                        <DownloadIcon className="w-5 h-5" />
                                        <span>下载汇报级 PDF</span>
                                    </>
                                )}
                            </button>
                        )}

                        <a 
                            href={selectedArticle.original_url} 
                            target="_blank" 
                            rel="noopener noreferrer" 
                            className="inline-flex items-center justify-center gap-2 px-5 py-3 text-sm font-medium text-slate-600 bg-slate-50 hover:bg-slate-100 rounded-xl transition-colors"
                        >
                            阅读原文 <ArrowRightIcon className="w-4 h-4 opacity-50" />
                        </a>
                    </div>

                    {/* Pro Tip Box */}
                    {htmlContent && showTip && (
                        <div className="relative bg-gradient-to-br from-indigo-50/80 to-blue-50/80 border border-indigo-100 rounded-xl p-4 flex items-start gap-3 animate-in fade-in-0 slide-in-from-top-2 mt-2">
                            <button 
                                onClick={() => setShowTip(false)} 
                                className="absolute top-2 right-2 text-indigo-300 hover:text-indigo-500 transition-colors"
                            >
                                <CloseIcon className="w-4 h-4" />
                            </button>
                            <div className="bg-white p-2 rounded-lg shadow-sm text-indigo-600 flex-shrink-0">
                                <SparklesIcon className="w-5 h-5" />
                            </div>
                            <div>
                                <h4 className="font-bold text-indigo-900 text-sm mb-1">开箱即用决策包</h4>
                                <p className="text-xs text-indigo-800/70 leading-relaxed">
                                    AI 已为您重构排版。下载后的 PDF 文档结构清晰、图文并茂，支持<strong>直接转换为 PPT</strong>，助您快速完成汇报材料。
                                </p>
                            </div>
                        </div>
                    )}
                </div>
            </div>

            {/* Content Area */}
            <div ref={contentRef} className="flex-1 bg-white overflow-hidden relative">
                {isLoadingHtml ? (
                    <div className="absolute inset-0 flex items-center justify-center bg-white z-10">
                        <div className="flex flex-col items-center gap-4">
                            <div className="relative w-16 h-16">
                                <div className="absolute inset-0 rounded-full border-4 border-slate-100"></div>
                                <div className="absolute inset-0 rounded-full border-4 border-indigo-600 border-t-transparent animate-spin"></div>
                            </div>
                            <div className="text-center">
                                <p className="text-base font-bold text-slate-800">AI 正在生成美化报告</p>
                                <p className="text-xs text-slate-400 mt-1">排版重构中，请稍候...</p>
                            </div>
                        </div>
                    </div>
                ) : htmlContent ? (
                    <iframe 
                        ref={iframeRef}
                        title="Article Content"
                        srcDoc={htmlContent}
                        className="w-full h-full border-none block bg-white"
                        sandbox="allow-same-origin allow-scripts allow-popups allow-forms allow-modals"
                    />
                ) : (
                    <div className="h-full overflow-y-auto p-8 md:p-12 custom-scrollbar bg-white">
                        {/* Fallback Message */}
                        <div className="mb-10 p-6 bg-amber-50 border border-amber-100 rounded-2xl flex items-center gap-4">
                            <div className="p-3 bg-white rounded-xl shadow-sm text-amber-500">
                                <SparklesIcon className="w-6 h-6" />
                            </div>
                            <div>
                                <p className="text-base font-bold text-amber-900">开箱即用报告生成中</p>
                                <p className="text-sm text-amber-700/80 mt-1">系统正在后台进行深度解析与排版美化，请稍后再来看看。</p>
                            </div>
                        </div>

                        <article 
                            className="prose prose-lg prose-slate max-w-none 
                                prose-headings:font-bold prose-headings:text-slate-900 prose-headings:tracking-tight
                                prose-p:text-slate-600 prose-p:leading-8 prose-p:mb-6 
                                prose-a:text-indigo-600 prose-a:no-underline hover:prose-a:underline prose-a:font-medium
                                prose-strong:text-slate-900 prose-strong:font-bold
                                prose-blockquote:border-l-4 prose-blockquote:border-indigo-500 prose-blockquote:bg-indigo-50/50 prose-blockquote:py-4 prose-blockquote:px-6 prose-blockquote:rounded-r-xl prose-blockquote:not-italic prose-blockquote:text-indigo-900
                                prose-img:rounded-2xl prose-img:shadow-lg prose-img:border prose-img:border-slate-100
                                prose-li:marker:text-indigo-400"
                            dangerouslySetInnerHTML={{ __html: fallbackArticleHtml }}
                        />
                    </div>
                )}
            </div>
        </aside>
    );
};
