
import React, { useMemo, useEffect, useState, useRef } from 'react';
import { InfoItem } from '../../types';
import { DocumentTextIcon, ArrowRightIcon, DownloadIcon, SparklesIcon } from '../icons';
import { getArticleHtml, downloadArticlePdf } from '../../api/intelligence';

// 为从CDN加载的 `marked` 库提供类型声明
declare global {
  interface Window {
    marked?: {
      parse(markdownString: string): string;
    };
  }
}

interface EvidenceTrailProps {
    selectedArticle: InfoItem | null;
}

export const EvidenceTrail: React.FC<EvidenceTrailProps> = ({ selectedArticle }) => {
    const [htmlContent, setHtmlContent] = useState<string | null>(null);
    const [isLoadingHtml, setIsLoadingHtml] = useState(false);
    const [isDownloading, setIsDownloading] = useState(false);
    const iframeRef = useRef<HTMLIFrameElement>(null);
    const contentRef = useRef<HTMLDivElement>(null);

    // Reset view when article changes and fetch HTML
    useEffect(() => {
        if (contentRef.current) {
            contentRef.current.scrollTop = 0;
        }
        
        setHtmlContent(null);
        
        // Check for valid ID (not a temporary random ID generated by frontend, marked with 'temp_')
        const isTempId = selectedArticle?.id && String(selectedArticle.id).startsWith('temp_');
        
        if (selectedArticle && !isTempId) {
            setIsLoadingHtml(true);
            getArticleHtml(selectedArticle.id)
                .then((html) => {
                    if (html) {
                        // Inject specific styles for better readability within the iframe
                        const printStyles = `
                            <style>
                                body { 
                                    font-family: 'HarmonyOS Sans SC', "Microsoft YaHei", "PingFang SC", -apple-system, sans-serif; 
                                    line-height: 1.8; 
                                    color: #1f2937; 
                                    padding: 24px; 
                                    max-width: 100%; 
                                    margin: 0;
                                    background-color: white;
                                    box-sizing: border-box;
                                }
                                @media (min-width: 768px) {
                                    body { padding: 32px 40px; }
                                }
                                img { max-width: 100%; border-radius: 8px; margin: 20px 0; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1); }
                                h1 { font-size: 22px; color: #111827; margin-bottom: 16px; font-weight: 700; line-height: 1.4; }
                                h2 { font-size: 18px; color: #1f2937; margin-top: 28px; margin-bottom: 12px; font-weight: 700; border-bottom: 1px solid #f3f4f6; padding-bottom: 8px; }
                                h3 { font-size: 16px; color: #374151; margin-top: 24px; margin-bottom: 10px; font-weight: 600; }
                                p { margin-bottom: 16px; text-align: justify; color: #4b5563; font-size: 16px; }
                                blockquote { border-left: 4px solid #6366f1; background: #f5f7ff; padding: 12px 16px; margin: 20px 0; border-radius: 0 8px 8px 0; color: #4338ca; font-size: 15px; }
                                ul, ol { margin-bottom: 16px; padding-left: 24px; color: #4b5563; }
                                li { margin-bottom: 6px; }
                                a { color: #4f46e5; text-decoration: none; }
                                a:hover { text-decoration: underline; }
                            </style>
                        `;
                        setHtmlContent(printStyles + html);
                    } else {
                        setHtmlContent(null);
                    }
                })
                .catch((err) => {
                    console.error("Failed to fetch article HTML", err);
                })
                .finally(() => {
                    setIsLoadingHtml(false);
                });
        }
    }, [selectedArticle]);

    const handleDownloadPdf = async () => {
        if (!selectedArticle) return;
        
        if (String(selectedArticle.id).startsWith('temp_')) {
             alert("该内容尚未入库，无法生成PDF。");
             return;
        }

        setIsDownloading(true);
        try {
            const blob = await downloadArticlePdf(selectedArticle.id);
            const url = window.URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = `${selectedArticle.title || 'report'}.pdf`;
            document.body.appendChild(a);
            a.click();
            a.remove();
            window.URL.revokeObjectURL(url);
        } catch (err: any) {
            console.error("PDF Download Error:", err);
            alert(err.message || "PDF 下载失败，请重试。");
        } finally {
            setIsDownloading(false);
        }
    };

    const fallbackArticleHtml = useMemo(() => {
        if (!selectedArticle || !selectedArticle.content) {
            return '';
        }

        if (window.marked && typeof window.marked.parse === 'function') {
            const markdownWithStyledImages = selectedArticle.content.replace(
                /!\[(.*?)\]\((.*?)\)/g,
                '<figure class="my-6"><img src="$2" alt="$1" class="rounded-lg w-full object-cover shadow-sm"><figcaption class="text-center text-xs text-gray-500 mt-2">$1</figcaption></figure>'
            );
            return window.marked.parse(markdownWithStyledImages);
        }

        const escapedContent = selectedArticle.content
            .replace(/&/g, "&amp;")
            .replace(/</g, "&lt;")
            .replace(/>/g, "&gt;");
        return escapedContent.split('\n').map(p => `<p>${p}</p>`).join('');

    }, [selectedArticle]);

    if (!selectedArticle) {
        return (
            <div className="h-full flex flex-col items-center justify-center text-center p-8 bg-white">
                <div className="w-20 h-20 bg-slate-50 rounded-full flex items-center justify-center mb-6 shadow-sm">
                    <DocumentTextIcon className="w-10 h-10 text-slate-300" />
                </div>
                <h3 className="font-bold text-xl text-slate-800 mb-2">AI 智能研报</h3>
                <p className="text-slate-500 text-sm">请从左侧选择一项情报</p>
            </div>
        );
    }

    return (
        <aside className="h-full flex flex-col bg-white overflow-hidden relative">
            {/* Header - Ultra Compact */}
            <div className="flex-shrink-0 border-b border-slate-100 bg-white/95 backdrop-blur z-20 px-4 py-3 md:px-5 md:py-3">
                
                {/* Desktop View: Single Row Layout */}
                <div className="hidden md:flex items-center justify-between gap-4">
                    <div className="flex items-center gap-3 overflow-hidden flex-1 min-w-0">
                        {/* Meta */}
                        <span className="flex-shrink-0 font-bold text-indigo-600 bg-indigo-50 border border-indigo-100 px-2 py-0.5 rounded text-xs">
                            {selectedArticle.source_name}
                        </span>
                        <span className="flex-shrink-0 text-slate-400 text-xs border-r border-slate-200 pr-3 mr-1">
                            {new Date(selectedArticle.publish_date || selectedArticle.created_at).toLocaleDateString('zh-CN', { month: 'numeric', day: 'numeric'})}
                        </span>
                        
                        {/* Title (Truncated) */}
                        <h3 className="font-bold text-slate-900 text-base truncate" title={selectedArticle.title}>
                            {selectedArticle.title}
                        </h3>
                    </div>

                    {/* Actions */}
                    <div className="flex items-center gap-2 flex-shrink-0">
                        {htmlContent && (
                            <button 
                                onClick={handleDownloadPdf}
                                disabled={isDownloading}
                                className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-bold text-indigo-600 bg-indigo-50 hover:bg-indigo-100 border border-indigo-200 rounded-lg transition-colors disabled:opacity-50"
                                title="下载 AI 重构的 PDF 报告"
                            >
                                {isDownloading ? (
                                    <div className="animate-spin w-3.5 h-3.5 border-2 border-indigo-400 border-t-transparent rounded-full"/>
                                ) : (
                                    <DownloadIcon className="w-3.5 h-3.5" />
                                )}
                                <span>下载报告</span>
                            </button>
                        )}
                        <a 
                            href={selectedArticle.original_url} 
                            target="_blank" 
                            rel="noopener noreferrer" 
                            className="p-1.5 text-slate-400 hover:text-slate-600 hover:bg-slate-100 rounded-lg transition-colors"
                            title="阅读原文"
                        >
                            <ArrowRightIcon className="w-4 h-4" />
                        </a>
                    </div>
                </div>

                {/* Mobile View: Stacked Layout */}
                <div className="md:hidden flex flex-col gap-2">
                    <div className="flex justify-between items-center">
                        <div className="flex items-center gap-2 text-xs">
                            <span className="font-bold text-indigo-600 bg-indigo-50 border border-indigo-100 px-2 py-0.5 rounded">
                                {selectedArticle.source_name}
                            </span>
                            <span className="text-slate-400">
                                {new Date(selectedArticle.publish_date || selectedArticle.created_at).toLocaleDateString('zh-CN', {month: 'numeric', day: 'numeric'})}
                            </span>
                        </div>
                        <div className="flex items-center gap-2">
                            {htmlContent && (
                                <button 
                                    onClick={handleDownloadPdf}
                                    disabled={isDownloading}
                                    className="p-1.5 text-indigo-600 bg-indigo-50 rounded-lg"
                                >
                                    {isDownloading ? <div className="animate-spin w-3.5 h-3.5 border-2 border-indigo-400 border-t-transparent rounded-full"/> : <DownloadIcon className="w-3.5 h-3.5" />}
                                </button>
                            )}
                            <a 
                                href={selectedArticle.original_url} 
                                target="_blank" 
                                rel="noopener noreferrer" 
                                className="p-1.5 text-slate-400 hover:text-slate-600 rounded-lg"
                            >
                                <ArrowRightIcon className="w-4 h-4" />
                            </a>
                        </div>
                    </div>
                    <h3 className="text-base font-bold text-slate-900 leading-snug line-clamp-2">
                        {selectedArticle.title}
                    </h3>
                </div>
            </div>

            {/* Content Area */}
            <div ref={contentRef} className="flex-1 bg-white overflow-hidden relative">
                {isLoadingHtml ? (
                    <div className="absolute inset-0 flex items-center justify-center bg-white z-10">
                        <div className="flex flex-col items-center gap-3">
                            <div className="animate-spin w-8 h-8 border-2 border-indigo-100 border-t-indigo-600 rounded-full"></div>
                            <p className="text-xs text-slate-400 font-medium">AI 正在生成美化报告...</p>
                        </div>
                    </div>
                ) : htmlContent ? (
                    <iframe 
                        ref={iframeRef}
                        title="Article Content"
                        srcDoc={htmlContent}
                        className="w-full h-full border-none block bg-white"
                        sandbox="allow-same-origin allow-scripts allow-popups allow-forms allow-modals"
                    />
                ) : (
                    <div className="h-full overflow-y-auto p-6 md:px-10 md:py-8 custom-scrollbar bg-white">
                        {/* Simple Fallback Notice */}
                        <div className="mb-6 p-3 bg-amber-50 border border-amber-100 rounded-lg flex items-center gap-3">
                            <SparklesIcon className="w-4 h-4 text-amber-500 flex-shrink-0" />
                            <p className="text-xs text-amber-700">排版引擎准备中，当前显示原始文本预览。</p>
                        </div>

                        <article 
                            className="prose prose-sm md:prose-base prose-slate max-w-none 
                                prose-headings:font-bold prose-headings:text-slate-900
                                prose-p:text-slate-600 prose-p:leading-relaxed prose-p:mb-4
                                prose-a:text-indigo-600 prose-a:no-underline hover:prose-a:underline
                                prose-img:rounded-lg prose-img:shadow-sm
                                prose-blockquote:border-l-4 prose-blockquote:border-indigo-400 prose-blockquote:bg-indigo-50 prose-blockquote:px-4 prose-blockquote:py-2 prose-blockquote:not-italic prose-blockquote:text-indigo-800"
                            dangerouslySetInnerHTML={{ __html: fallbackArticleHtml }}
                        />
                    </div>
                )}
            </div>
        </aside>
    );
};
