import React, { useState } from 'react';
import { CloseIcon } from './icons';
import { Subscription } from '../types';

interface AddSubscriptionModalProps {
  onClose: () => void;
  onSave: (subscription: Omit<Subscription, 'id' | 'keywords' | 'query' | 'newItemsCount'>) => void;
}

export const AddSubscriptionModal: React.FC<AddSubscriptionModalProps> = ({ onClose, onSave }) => {
    const [pointName, setPointName] = useState('');
    const [sourceName, setSourceName] = useState('');
    const [pointUrl, setPointUrl] = useState('');
    const [cronSchedule, setCronSchedule] = useState('0 9 * * *'); // Default value from API docs

    const isFormValid = pointName.trim() && sourceName.trim() && pointUrl.trim() && cronSchedule.trim();

    const handleSave = () => {
        if (!isFormValid) return;
        // Fix: Added dummy values for missing properties to satisfy the over-specified type from App.tsx.
        // The backend will generate the real values for these fields upon creation.
        onSave({
            point_name: pointName,
            source_name: sourceName,
            point_url: pointUrl,
            cron_schedule: cronSchedule,
            source_id: '', // This will be generated by the backend
            is_active: true,
            last_triggered_at: null,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
        });
    };

    return (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4">
            <div className="bg-white rounded-2xl w-full max-w-lg relative shadow-xl transform transition-all animate-in fade-in-0 zoom-in-95">
                <div className="p-6 border-b border-gray-200 flex justify-between items-center">
                    <h3 className="text-lg font-semibold text-gray-900">
                        添加新的情报关注点
                    </h3>
                    <button onClick={onClose} className="text-gray-400 hover:text-gray-700 transition-colors">
                        <CloseIcon className="w-6 h-6" />
                    </button>
                </div>
                
                <div className="p-6">
                    <p className="text-sm text-gray-600 mb-4">输入情报采集点的详细信息。如果情报源名称不存在，系统将自动创建。</p>
                    <div className="space-y-4">
                        <div>
                            <label className="text-sm font-medium text-gray-700">情报点名称 (例如 "前沿技术")</label>
                            <input type="text" value={pointName} onChange={e => setPointName(e.target.value)} className="mt-1 w-full p-2 bg-gray-50 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"/>
                        </div>
                        <div>
                            <label className="text-sm font-medium text-gray-700">情报源名称 (例如 "虎嗅网")</label>
                            <input type="text" value={sourceName} onChange={e => setSourceName(e.target.value)} className="mt-1 w-full p-2 bg-gray-50 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"/>
                        </div>
                        <div>
                            <label className="text-sm font-medium text-gray-700">采集点 URL</label>
                            <input type="url" value={pointUrl} onChange={e => setPointUrl(e.target.value)} placeholder="https://www.huxiu.com/channel/103.html" className="mt-1 w-full p-2 bg-gray-50 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"/>
                        </div>
                        <div>
                            <label className="text-sm font-medium text-gray-700">CRON 调度 (例如 "0 9 * * *")</label>
                            <input type="text" value={cronSchedule} onChange={e => setCronSchedule(e.target.value)} className="mt-1 w-full p-2 bg-gray-50 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"/>
                        </div>
                    </div>
                </div>

                <div className="px-6 py-4 bg-gray-50 border-t border-gray-200 flex justify-end space-x-3 rounded-b-2xl">
                    <button onClick={onClose} className="py-2 px-4 bg-white border border-gray-300 text-gray-700 rounded-lg font-semibold text-sm hover:bg-gray-100 transition-colors">
                        取消
                    </button>
                    <button onClick={handleSave} disabled={!isFormValid} className="py-2 px-4 bg-blue-600 text-white rounded-lg font-semibold text-sm hover:bg-blue-700 disabled:bg-blue-300">
                        保存关注点
                    </button>
                </div>
            </div>
        </div>
    );
};