import React, { useRef, useEffect, useState } from 'react';
import { ReportSection, StepId } from './types';
import VisualEditor from '../../../shared/VisualEditor';
import { marked } from 'marked';
import { RefreshIcon, DocumentTextIcon, ChartIcon, CheckCircleIcon, SparklesIcon, ServerIcon } from '../../../icons';

interface ReportCanvasProps {
    sections: Record<StepId, ReportSection>;
    currentStep: StepId;
    techName: string;
}

const stepsOrder: StepId[] = ['route', 'risk', 'solution', 'compare'];

// --- 自适应缩放的视觉组件包装器 ---
const VisualWidget: React.FC<{ html: string }> = ({ html }) => {
    const containerRef = useRef<HTMLDivElement>(null);
    const [width, setWidth] = useState(0);

    useEffect(() => {
        if (!containerRef.current) return;
        const ro = new ResizeObserver(entries => {
            for (const entry of entries) {
                if (entry.contentRect.width > 0) {
                    setWidth(entry.contentRect.width);
                }
            }
        });
        ro.observe(containerRef.current);
        return () => ro.disconnect();
    }, []);

    // 16:9 Aspect Ratio
    // Calculate height based on current width
    const height = width * (9/16);
    
    // Calculate Scale: Standard canvas width is usually 1600 in our templates
    const scale = Math.max(0.3, width / 1600);

    return (
        <div className="mt-8 border border-slate-200 rounded-xl overflow-hidden shadow-sm bg-slate-50 relative group">
            {/* Header Bar - Solves the floating label issue */}
            <div className="h-10 px-4 bg-white border-b border-slate-200 flex justify-between items-center">
                <div className="flex items-center gap-2 text-xs font-bold text-slate-600">
                    <ChartIcon className="w-4 h-4 text-indigo-500" />
                    <span>可视化分析图表</span>
                </div>
                <div className="text-[10px] text-slate-400 font-mono">
                    Generated by TechVisualizer
                </div>
            </div>
            
            {/* Canvas Container */}
            <div ref={containerRef} style={{ height: height || 450, position: 'relative' }} className="w-full bg-slate-100 flex items-center justify-center">
                 <VisualEditor 
                    initialHtml={html} 
                    onSave={() => {}} 
                    scale={scale}
                    canvasSize={{ width: 1600, height: 900 }}
                    hideToolbar={true} // Clean view
                 />
            </div>
        </div>
    );
};

export const ReportCanvas: React.FC<ReportCanvasProps> = ({ sections, currentStep, techName }) => {
    const bottomRef = useRef<HTMLDivElement>(null);

    // Auto scroll to bottom when new content arrives
    useEffect(() => {
        if (bottomRef.current) {
            bottomRef.current.scrollIntoView({ behavior: 'smooth' });
        }
    }, [sections]);

    const renderSection = (key: StepId) => {
        const section = sections[key];
        if (section.status === 'pending' && !section.markdown) return null;
        
        const isGenerating = section.status === 'generating';
        const isDone = section.status === 'done' || section.status === 'review';

        return (
            <div key={key} className="mb-10 animate-in fade-in slide-in-from-bottom-6 duration-700 relative pl-4 md:pl-0">
                
                {/* 左侧时间轴线条 (Desktop) */}
                <div className="hidden md:block absolute left-[-29px] top-0 bottom-0 w-0.5 bg-slate-200 last:bottom-auto last:h-full"></div>
                <div className={`hidden md:flex absolute left-[-36px] top-0 w-4 h-4 rounded-full border-2 items-center justify-center bg-slate-50 transition-colors z-10 ${isDone ? 'border-indigo-500' : 'border-slate-300'}`}>
                    {isDone && <div className="w-2 h-2 bg-indigo-500 rounded-full"></div>}
                </div>

                <div className="flex flex-col bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden transition-all hover:shadow-md">
                    {/* Section Header */}
                    <div className="px-6 py-5 border-b border-slate-100 bg-gradient-to-r from-slate-50/80 to-white flex items-center justify-between">
                        <div className="flex items-center gap-3">
                            <div className={`p-2 rounded-lg text-white shadow-sm transition-colors ${isGenerating ? 'bg-indigo-500 animate-pulse' : 'bg-indigo-600'}`}>
                                {key === 'compare' ? <ChartIcon className="w-5 h-5"/> : <DocumentTextIcon className="w-5 h-5"/>}
                            </div>
                            <div className="flex flex-col">
                                <div className="flex items-center gap-2">
                                    <h2 className="text-lg font-extrabold text-slate-800 tracking-tight">{section.title}</h2>
                                    {section.usedModel && (
                                        <span className="text-[9px] font-mono text-slate-400 bg-slate-50 px-1.5 py-0.5 rounded border border-slate-100 flex items-center gap-1">
                                            <ServerIcon className="w-2.5 h-2.5" />
                                            {section.usedModel}
                                        </span>
                                    )}
                                </div>
                                {isGenerating && <p className="text-xs text-indigo-500 font-medium mt-0.5">AI 正在深度分析中...</p>}
                            </div>
                        </div>
                        {isDone && <CheckCircleIcon className="w-5 h-5 text-green-500 opacity-50" />}
                    </div>

                    <div className="p-6 md:p-8">
                        {/* Markdown Content */}
                        <div className="prose prose-slate prose-sm md:prose-base max-w-none text-slate-600 leading-relaxed">
                            <div dangerouslySetInnerHTML={{ __html: marked.parse(section.markdown) as string }} />
                        </div>

                        {/* HTML Widget (Integrated) */}
                        {section.html && (
                            <VisualWidget html={section.html} />
                        )}
                        
                        {/* Generating Placeholder if needed */}
                        {isGenerating && !section.html && !section.markdown && (
                            <div className="flex flex-col items-center justify-center py-12 text-slate-400 gap-3">
                                <RefreshIcon className="w-6 h-6 animate-spin text-indigo-400"/>
                                <span className="text-sm font-medium">正在生成内容...</span>
                            </div>
                        )}
                    </div>
                </div>
            </div>
        );
    };

    return (
        <div className="h-full flex flex-col bg-[#f8fafc]">
            {/* Canvas Content */}
            <div className="flex-1 overflow-y-auto p-4 md:p-12 custom-scrollbar">
                <div className="max-w-4xl mx-auto relative md:pl-8">
                    {/* Timeline Vertical Line Container */}
                    <div className="hidden md:block absolute left-0 top-0 bottom-0 w-px bg-transparent"></div>

                    {techName ? (
                        <>
                            {stepsOrder.map(step => renderSection(step))}
                            {/* Scroll Anchor */}
                            <div ref={bottomRef} className="h-20"></div>
                        </>
                    ) : (
                        <div className="flex flex-col items-center justify-center h-[60vh] text-slate-400 opacity-60">
                            <div className="w-24 h-24 bg-white rounded-full flex items-center justify-center mb-6 shadow-sm border border-slate-200">
                                <SparklesIcon className="w-12 h-12 text-indigo-300"/>
                            </div>
                            <h3 className="text-xl font-bold text-slate-700">技术决策评估助手</h3>
                            <p className="text-sm mt-2 max-w-xs text-center leading-relaxed">
                                请在右侧对话框输入您想要评估的技术主题，AI 将为您生成深度分析报告。
                            </p>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
};